services:
  oracle:
    image: 'gvenzl/oracle-free:latest'
    environment:
      - 'ORACLE_PASSWORD=secret'
    ports:
      - '1521'

#  db:
#    container_name: "postgresDB"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Gfdtk123
#      ports: "5432:5432"
#      volumes:
#        - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
#        - db-data:/var/lib/postgresql/data